name: Bump module version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    uses: urob/zmk-modules-actions/.github/workflows/upgrade-module.yml@main
