name: Run tests

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "tests/**"
      - "src/**"
      - "include/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "tests/**"
      - "src/**"
      - "include/**"

jobs:
  build:
    uses: urob/zmk-modules-actions/.github/workflows/run-tests.yml@main
