name: Run tests

on:
  workflow_dispatch:
  push:
    paths:
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"
  pull_request:
    paths:
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"

jobs:
  test:
    uses: urob/zmk-modules-actions/.github/workflows/run-tests.yml@v1
