name: Upgrade to latest ZMK version

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 22:00 UTC (17:00 ET)
    - cron: "0 22 * * *"

jobs:
  build:
    uses: urob/zmk-modules-actions/.github/workflows/upgrade-zmk.yml@main
    permissions:
      contents: write
    secrets: inherit
